name: Build, Lint, Test and Release
on:
  push:
    branches:
      # Currently disaled this workflow.
      # To enable this feature, change the line below
      - change-this-to-default-branch-to-enable-this-workflow

concurrency: release

jobs:
  build-lint-test:
    uses: ./.github/workflows/build-lint-test.yml
    permissions:
      actions: write
      contents: read

  release:
    needs: build-lint-test

    permissions:
      # Uncommment the following line if you enable a package provenance
      # id-token: write
      # create a PR
      contents: write
      pull-requests: write

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout the source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 22.14.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm build

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@c8bada60c408975afd1a20b3db81d6eee6789308 # v1.4.9
        with:
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
